name: Sync Notes to Website

on:
  push:
    branches:
      - main  # 监听笔记仓库的 main 分支，触发同步
  schedule:
    - cron: '0 0 * * *'  # 每天午夜同步一次，可以根据需要修改

jobs:
  sync-notes:
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
      # 1. Checkout 网站仓库
      - name: Checkout Website Repository
        uses: actions/checkout@v3

      # 2. Checkout 笔记仓库
      - name: Checkout Notes Repository
        uses: actions/checkout@v3
        with:
          repository: coffee8848/Discrete-Math  # 替换为你的笔记仓库名称
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 自动生成的 token
          path: notes  # 将笔记仓库内容下载到 'notes' 文件夹

      # 3. 将笔记文件同步到网站仓库的 _posts 目录
      - name: Copy Notes to Website _posts Directory
        run: |
          mkdir -p ./_posts
          for file in notes/**/*.md; do
            folder_name=$(basename "$(dirname "$file")")
            cp "$file" "./_posts/$(basename "$file")"
          done

      # 4. 复制图片到网站仓库的相关目录
      - name: Copy Images to Website
        run: |
          mkdir -p ./_assets/images
          cp -r notes/**/*.png notes/**/*.jpg notes/**/*.jpeg notes/**/*.gif ./_assets/images/

      # 5. 提交并推送更改到网站仓库
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"  # 配置 Git 用户名
          git config --global user.email "actions@github.com"  # 配置 Git 用户邮箱
          git add .  # 添加更改
          git commit -m "Sync notes from Discrete-Math repository"  # 提交更改
          git push  # 推送到网站仓库的 main 分支
