name: Sync Notes from Notes Repository

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行
  push:
    branches:
      - main  # 当主分支有更新时触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the NoteDisplay repository
        uses: actions/checkout@v2

      - name: Checkout the Notes repository
        uses: actions/checkout@v2
        with:
          repository: coffee8848/Discrete-Math  # 替换为你的笔记库仓库名
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copy notes to the NoteDisplay repository
        run: |
          # 创建 _notes 目录
          mkdir -p _notes

          # 遍历笔记库中的所有文件夹和md文件，按章节结构复制到 _notes 文件夹
          for chapter in $(find ../Discrete-Math -type d); do
            # 提取章节名称
            chapter_name=$(basename "$chapter")
            # 创建对应的章节目录
            mkdir -p "_notes/$chapter_name"
            # 复制该章节中的所有 md 文件到 _notes 目录
            cp "$chapter"/*.md "_notes/$chapter_name/"
            # 复制该章节中的所有图片文件到 _notes 目录
            cp -r "$chapter/images" "_notes/$chapter_name/"
          done

      - name: Build the Jekyll site
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "自动同步笔记更新"
          git push
